name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'    # Set Node.js version
  AZURE_WEBAPP_NAME: lookbook-nextjs-app   # Set this to your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # Set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Build Environment
        run: |
          # Create environment variables
          echo "CI=true" >> .env.local
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_URL=https://wwjuohjstrcyvshfuadr.supabase.co" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.local
          echo "GOOGLE_APPLICATION_CREDENTIALS=./dummy-credentials.json" >> .env.local
          echo "NEXT_PUBLIC_WEBSOCKET_URL=wss://lookbook-nextjs-app.azurewebsites.net/api/gemini-live" >> .env.local
          echo "NEXT_TELEMETRY_DISABLED=1" >> .env.local
          
          # Create dummy credentials
          echo "{}" > ./dummy-credentials.json
          
          # Clean any existing files
          rm -f package-lock.json
          rm -f yarn.lock
          rm -rf node_modules
          rm -rf .next

      - name: Install Production Dependencies Only
        run: |
          # Install only production dependencies
          npm install --omit=dev --no-package-lock

      - name: Install Next.js
        run: npm install next@15.2.4 --no-package-lock

      - name: Build Next.js Application
        run: |
          # Set next.config.js to disable ESLint
          echo "module.exports = { eslint: { ignoreDuringBuilds: true } };" > next.config.js
          
          # Build the application
          npx next build
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
          NODE_OPTIONS: "--max-old-space-size=4096"
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: "https://wwjuohjstrcyvshfuadr.supabase.co"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: "./dummy-credentials.json"
          NEXT_PUBLIC_WEBSOCKET_URL: "wss://lookbook-nextjs-app.azurewebsites.net/api/gemini-live"

      - name: Create Zip Artifact
        run: zip -r release.zip . -x "node_modules/*" ".git/*" ".next/cache/*"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip 